# Generated by Django 6.0.2 on 2026-03-02 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprinttasks',
            name='status',
            field=models.CharField(choices=[('To Do', 'To Do'), ('In Progress', 'In Progress'), ('Done', 'Done'), ('Blocked', 'Blocked')], max_length=50),
        ),
    ]
