# Generated by Django 6.0.2 on 2026-02-27 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TeamMembers',
            fields=[
                ('team_member_id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('Manager', 'Manager'), ('Developer', 'Developer'), ('Tester', 'Tester')], max_length=50)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.users')),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.teams')),
            ],
        ),
    ]
